### ISSUE TITLE
Practica 1 de la segunda unidad del equipo de Eduardo Tomas Feria Ortiz

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/practica-de-conjuntos-team-eduardo-tomas-1as#1]
[PRACTICA1_2U_OPERACIONES_DE_CONJUNTOS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-conjuntos-team-eduardo-tomas-1as/files/7317009/PRACTICA1_2U_OPERACIONES_DE_CONJUNTOS_EQUIPO_EDUARDO_TOMAS_FERIA_ORTIZ.pdf)

**Comment by lucero012** [comment]
le ponemos el 13 % porque viendo la rubrica no cumple con algunos puntos por ejemplo: descripción de material, las figuras  no tiene descripción , 2 ejercicios no están bien resueltos (Ejercicio 6 y 8)y viene un grafica de mas en  ( los ejercicios del producto cartesiano)

**Comment by josealfredo79** [comment]
Hay que completar el trabajo...bien hecho y revisado
